### ISSUE TITLE
Trouble running the QGIS-Model

### ISSUE THREAD

**Issue by charliewahl** [GrHalbgott/Plants-vs-CO2#5]
After following the given instructions on downloading the required Data for the GGIS-Model putting it in as specified, the following Error accured:

<img width="415" alt="isssue" src="https://user-images.githubusercontent.com/93196814/155989269-fbe7c6dc-b10b-4f96-9894-7da1a3bb4c3b.png">

To keep it as simple as possible I planned on using Heidelberg as my ROI.  Therefore I could leave the column name "Name_3" and the CRS as it. For the GADM Shapefile input I used gadm40_DEU_3 and the two Raster Bands T32UMV_20181111T103241_B04_10m.jp2" and "T32UMV_20181111T103241_B08_10m.jp2" . As far as I understood your Scipt, this should work out together right?
Now, as soon as I hit "run", a first it seems to run perfectly but stops pretty quickly after giving out the Error shown in the screenshot above. Do you have any idea why?

**Comment by GrHalbgott** [comment]
Thanks for the feedback! Can you run it again and copy the whole protocol into this issue? Additionally, can you open the model in the Graphic Modeler, take a screenshot and post it here together with the protocol? I have some ideas what the problem could be, but the error message doesn't give enough information.

**Comment by GrHalbgott** [comment]
The problem has been fixed by using another Raster calculator. The one from QGIS seems to be problematic to use when calculating inside a model.
